language: ruby
rvm: 2.4.2
gemfile:
  - Gemfile
  - test/gemfiles/activerecord50.gemfile
sudo: false
before_install: gem install bundler
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
